# -*- coding: utf-8 -*-
"""SatieToNationalAnthem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1af0Q2ZFbst9UB4RURcj42xl2C8lsNQiQ
"""

!apt-get update -qq && apt-get install -qq libfluidsynth1 fluid-soundfont-gm build-essential libasound2-dev libjack-dev
!pip install -qU pyfluidsynth pretty_midi
!pip install -qU magenta



!gsutil -q -m cp -R gs://download.magenta.tensorflow.org/models/music_vae/colab2/checkpoints/mel_2bar_big.ckpt.* /content/

from magenta.models.music_vae import configs
from magenta.models.music_vae.trained_model import TrainedModel

# モデルの初期化
music_vae = TrainedModel(
      configs.CONFIG_MAP["cat-mel_2bar_big"], 
      batch_size=4,  # 一度に処理するデータ数
      checkpoint_dir_or_path="/content/mel_2bar_big.ckpt")

import note_seq

generated = music_vae.sample(n=5,  # 生成数
                             length=64,  # ステップ数
                             temperature=1.0)  # 温度

for ns in generated:
    note_seq.plot_sequence(ns)
    note_seq.play_sequence(ns, synth=note_seq.fluidsynth)

import magenta
import note_seq
from note_seq.protobuf import music_pb2

# 最初のNoteSeqence
kira2_start = music_pb2.NoteSequence()
pg = 10

#
# notesにnoteを追加
kira2_start.notes.add(pitch=66, start_time=0.0, end_time=0.4, velocity=80, program=pg)
kira2_start.notes.add(pitch=69, start_time=0.4, end_time=0.8, velocity=80, program=pg)
kira2_start.notes.add(pitch=67, start_time=0.8, end_time=1.2, velocity=80, program=pg)
kira2_start.notes.add(pitch=66, start_time=1.2, end_time=1.6, velocity=80, program=pg)
kira2_start.notes.add(pitch=61, start_time=1.6, end_time=2.0, velocity=80, program=pg)
kira2_start.notes.add(pitch=59, start_time=2.0, end_time=2.4, velocity=80, program=pg)
kira2_start.notes.add(pitch=61, start_time=2.4, end_time=2.8, velocity=80, program=pg)
kira2_start.notes.add(pitch=62, start_time=2.8, end_time=3.2, velocity=80, program=pg)
kira2_start.notes.add(pitch=57, start_time=3.2, end_time=4.4, velocity=80, program=pg)

kira2_start.total_time = 4.4 
kira2_start.tempos.add(qpm=75);

note_seq.plot_sequence(kira2_start)
note_seq.play_sequence(kira2_start, synth=note_seq.fluidsynth)

# 最後のNoteSeqence
kira2_mid = music_pb2.NoteSequence()
pg=11

kira2_mid.notes.add(pitch=58, start_time=0.0, end_time=0.6, velocity=80, program=pg)
kira2_mid.notes.add(pitch=60, start_time=0.6, end_time=0.8, velocity=80, program=pg)
kira2_mid.notes.add(pitch=62, start_time=0.8, end_time=1.0, velocity=80, program=pg)
kira2_mid.notes.add(pitch=63, start_time=1.0, end_time=1.2, velocity=80, program=pg)

kira2_mid.notes.add(pitch=65, start_time=1.2, end_time=2.0, velocity=80, program=pg)
kira2_mid.notes.add(pitch=58, start_time=2.0, end_time=2.2, velocity=80, program=pg)
kira2_mid.notes.add(pitch=60, start_time=2.2, end_time=2.4, velocity=80, program=pg)

kira2_mid.notes.add(pitch=62, start_time=2.4, end_time=3.0, velocity=80, program=pg)
kira2_mid.notes.add(pitch=63, start_time=3.0, end_time=3.2, velocity=80, program=pg)
kira2_mid.notes.add(pitch=60, start_time=3.2, end_time=3.6, velocity=80, program=pg)
kira2_mid.notes.add(pitch=58, start_time=3.6, end_time=4.4, velocity=80, program=pg)

kira2_mid.total_time = 4.4
kira2_mid.tempos.add(qpm=75); 

note_seq.plot_sequence(kira2_mid)
note_seq.play_sequence(kira2_mid, synth=note_seq.fluidsynth)  # NoteSequenceの再生





n_seq = 4 # 曲のNoteSeqence数（最初と最後を含む）

# NoteSeqenceを複数生成し、リストに格納
gen_seq1 = music_vae.interpolate(
    kira2_start,  # 最初のNoteSeqence
    kira2_mid,  # 最後のNoteSeqence
    #kira2_end,
    num_steps=n_seq,
    length=32)


# NoteSeqenceを全て結合し、1つの曲に
interp_seq1 = note_seq.sequences_lib.concatenate_sequences(gen_seq1)

note_seq.plot_sequence(interp_seq1)
note_seq.play_sequence(interp_seq1, synth=note_seq.fluidsynth)

from google.colab import files

note_seq.sequence_proto_to_midi_file(interp_seq, "SatieToUSA.mid")  #MIDI　データに変換し保存
files.download("SatieToUSA.mid")  # ダウンロード