# -*- coding: utf-8 -*-
"""testpython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K5373CQVK44btE_RwdY2pHIt9KKVfAja
"""

# variables
a = 10
b = 20

# function
def func():
    return "Do you enjoy programming?"

# Output text to the screen
print("Welcome to my website!")

if __name__ == '__main__':
    print("Have a nice day!")