# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zj04P-rk4_Fvd5NcMKSIovWXmynuBwoO
"""

#numpy, pandas, streamlitのパッケージインストール
import numpy as np
import pandas as pd
!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# #streamlitメインの処理を/content/app.pyに保存
# #%%writefile app.py以降の記述を変えれば色々とstreamlitを試せる
# #試す内容はインプット元の②の色々なサンプルコードを参照
# #以下は5秒のカウントダウン後に風船を飛ばすコードを記載
# 
# %%writefile app.py
# import time
# 
# import streamlit as st
# 
# 
# def main():
#     status_area = st.empty()
# 
#     # カウントダウン
#     count_down_sec = 5
#     for i in range(count_down_sec):
#         # プレースホルダーに残り秒数を書き込む
#         status_area.write(f'{count_down_sec - i} sec left')
#         # スリープ処理を入れる
#         time.sleep(1)
# 
#     # 完了したときの表示
#     status_area.write('Done!')
#     # 風船飛ばす
#     st.balloons()
# 
# 
# if __name__ == '__main__':
#     main()
#

#Google Colabのファイルブラウザを起動し、エディタでapp.pyを開く
#動作上は必須作業ではない
from google.colab import files
files.view("/content")
files.view("app.py")

#次のコード実行する際にprotobufのバージョン起因のエラーが出るので、それを直すおまじない
!pip install --upgrade protobuf

#streamlitをlocaltunnelのトンネルで起動
#実行画面に出るyour url is:のurlに接続し、ブラウザの別タブに移動
#Click to Continueでstreamlitの動作を確認
#確認が終わったらこのセルの実行を停止する
!streamlit run app.py & sleep 3 && npx localtunnel --port 8501